#!/bin/bash

PROGNAME="$( basename $0 )"

cwd=`pwd -P`

TARGET_FILE=$0
while [ "$TARGET_FILE" != "" ]; do
    cd `dirname $TARGET_FILE`
    FILENAME=`basename $TARGET_FILE`
    TARGET_FILE=`readlink $FILENAME`
done
DIRECTORY=`pwd -P`
cd $cwd

PARAM=()
HELP=0
COMMAND=""
SUBCOMMAND=""
for OPT in "$@"; do
  case "${OPT}" in
    'init' )
      COMMAND="init"; shift
      ;;
    'add' )
      COMMAND="add"; shift

      case "$1" in
        'registry' )
          SUBCOMMAND="registry"; shift
          ;;
        'package' )
          SUBCOMMAND="package"; shift
          ;;
        * )
          ;;
      esac
      ;;
    'help' )
      HELP=1; shift
      ;;
    '-h' | '--help' )
      HELP=1; shift
      ;;
    '--' | '-' )
      shift
      PARAM+=( "$@" )
      break
      ;;
    -* )
      echo "${PROGNAME}: illegal option -- '$( echo $1 | sed 's/^-*//' )'" 1>&2
      exit 1
      ;;
    * )
      if [[ -n "$1" ]] && [[ ! "$1" =~ ^-+ ]]; then
        PARAM+=( "$1" ); shift
      fi
      ;;
  esac
done

source "${DIRECTORY}/scripts/lib/usage.sh"
source "${DIRECTORY}/scripts/lib/runner.sh"
