#!/bin/bash

PROGNAME="$( basename $0 )"

cwd=`pwd -P`

TARGET_FILE=$0
while [ "$TARGET_FILE" != "" ]; do
    cd `dirname $TARGET_FILE`
    FILENAME=`basename $TARGET_FILE`
    TARGET_FILE=`readlink $FILENAME`
done
DIRECTORY=`pwd -P`
cd "$cwd"

source "${DIRECTORY}/scripts/lib/option.sh"
source "${DIRECTORY}/scripts/lib/usage.sh"
source "${DIRECTORY}/scripts/lib/runner.sh"
